-- SQL Update Script: All Modules - Sections and Lessons
-- Generated by compare-json-and-generate-sql.mjs
-- Date: 2026-01-05T22:06:37.223Z
--
-- This script updates sections and lessons in all modules to match
-- the reference JSON structure (course-metadata_copy.json)
--
-- WARNING: Review all changes before executing!
-- Backup your database before running this script.
--
-- Total changes: 6
--   - Section title changes: 1
--   - Section order changes: 0
--   - Lesson section changes: 5
--   - Lesson order changes: 0

BEGIN;

-- Update section title: section-04-03 (Module: module-04)
UPDATE sections SET title = 'Manejo da Cultura do Milho', "updatedAt" = NOW() WHERE "sectionId" = 'section-04-03';

-- Move lesson to correct section: lesson-04-02-01 (Silagem de milho) (Module: module-04)
UPDATE lessons SET "sectionId" = 'section-04-01', "updatedAt" = NOW() WHERE "lessonId" = 'lesson-04-02-01';

-- Move lesson to correct section: lesson-04-01-01 (Principais desafios na produção de silagem) (Module: module-04)
UPDATE lessons SET "sectionId" = 'section-04-02', "updatedAt" = NOW() WHERE "lessonId" = 'lesson-04-01-01';

-- Move lesson to correct section: lesson-04-01-15 (Doenças na cultura de milho) (Module: module-04)
UPDATE lessons SET "sectionId" = 'section-04-03', "updatedAt" = NOW() WHERE "lessonId" = 'lesson-04-01-15';

-- Move lesson to correct section: lesson-05-05-06 (Resolução do exercício - Fluxo de caixa X Custo de) (Module: module-05)
UPDATE lessons SET "sectionId" = 'section-05-01', "updatedAt" = NOW() WHERE "lessonId" = 'lesson-05-05-06';

-- Move lesson to correct section: lesson-05-01-06 (Conceitos importantes na gestão econômica) (Module: module-05)
UPDATE lessons SET "sectionId" = 'section-05-05', "updatedAt" = NOW() WHERE "lessonId" = 'lesson-05-01-06';

COMMIT;

-- Verify changes by module:
-- SELECT "moduleId", "sectionId", title, "order" FROM sections WHERE "moduleId" = 'module-XX' ORDER BY "order";
-- SELECT "moduleId", "lessonId", title, "sectionId", "order" FROM lessons WHERE "moduleId" = 'module-XX' ORDER BY "sectionId", "order";
